# Chapter 14: Data Indexing and Selection

## 14.1 Data Selection in Series

### 14.1.1 Series as Dictionary

Series give mapping key-value as dictionary

In [1]:
import pandas as pd
import numpy as np

data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
print(data)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [7]:
# access by key as dictionary
print(data['b'])

# Check for key existence
print('a' in data)

# Check key list
print(data.keys())

# Check (key, value) pairs with items()
print(list(data.items()))

0.5
True
Index(['a', 'b', 'c', 'd'], dtype='str')
[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

### 14.1.2 Series as One-Dimensional Array

In [8]:
# Slicing
print(data['a':'c'])

a    0.25
b    0.50
c    0.75
dtype: float64

💡 Note: When slicing with an explicit index, the end index is included!

In [9]:
# slicing
print(data[0:2])

a    0.25
b    0.50
dtype: float64

💡 When slicing by implicit integer index, the end index is excluded! (NumPy style)

In [10]:
# masking (Boolean array)
print(data[(data > 0.3) & (data < 0.8)])

b    0.50
c    0.75
dtype: float64

In [13]:
# Fancy indexing
print(data[['a', 'b']])

a    0.25
b    0.50
dtype: float64

## 14.2 Indexers: loc and iloc

### 14.2.1 loc (Location)

In [16]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
print(data)

1    a
3    b
5    c
dtype: str

In [18]:
# loc: 항상 명시적 인덱스를 참조
print(data.loc[1])
print(data.loc[1:3])

a
1    a
3    b
dtype: str

💡 loc includes the end when slicing based on index labels.

### 14.2.2 iloc (Integer Location)

In [22]:
# iloc: 항상 암시적 Python 스타일 인덱스를 참조
print(data.iloc[1])
print(data.iloc[1:3])

b
3    b
5    c
dtype: str

💡 iloc is based on the index position. Same as NumPy style!

## 14.3 Data Selection in DataFrames

### 14.3.1 DataFrame as Dictionary

In [26]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'Florida': 170312, 'New York': 141297,
                  'Pennsylvania': 119280})
pop = pd.Series({'California': 39538223, 'Texas': 29145505,
                 'Florida': 21538187, 'New York': 20201249,
                 'Pennsylvania': 13002700})
data = pd.DataFrame({'area': area, 'pop': pop})
data

                area       pop
California    423967  39538223
Texas         695662  29145505
Florida       170312  21538187
New York      141297  20201249
Pennsylvania  119280  13002700

In [27]:
print(data['area'])

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

💡 Accessing properties is convenient, but cannot be used if the column name conflicts with the method name or contains spaces!

In [29]:
# add new column (like dictionary)
data['density'] = data['pop'] / data['area']
data

                area       pop     density
California    423967  39538223   93.257784
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvania  119280  13002700  109.009893

### 14.3.2 DataFrame as Two-Dimensional Array

In [30]:
print(data.values)

[[4.23967000e+05 3.95382230e+07 9.32577842e+01]
 [6.95662000e+05 2.91455050e+07 4.18960717e+01]
 [1.70312000e+05 2.15381870e+07 1.26463121e+02]
 [1.41297000e+05 2.02012490e+07 1.42970120e+02]
 [1.19280000e+05 1.30027000e+07 1.09009893e+02]]

In [31]:
print(data.T)

           California         Texas       Florida      New York  Pennsylvania
area     4.239670e+05  6.956620e+05  1.703120e+05  1.412970e+05  1.192800e+05
pop      3.953822e+07  2.914550e+07  2.153819e+07  2.020125e+07  1.300270e+07
density  9.325778e+01  4.189607e+01  1.264631e+02  1.429701e+02  1.090099e+02

In [33]:
# By iloc indexing as Numpy style
print(data.iloc[:3, :2])

              area       pop
California  423967  39538223
Texas       695662  29145505
Florida     170312  21538187

In [34]:
# By loc indexing as label style
print(data.loc['Florida':'New York', 'area':'pop'])

            area       pop
Florida   170312  21538187
New York  141297  20201249

In [35]:
# By loc masking and fancy indexing
print(data.loc[data.density > 120, ['pop', 'density']])

               pop     density
Florida   21538187  126.463121
New York  20201249  142.970120

In [36]:
# Modify value
data.iloc[0, 2] = 90
data

                area       pop     density
California    423967  39538223   90.000000
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvania  119280  13002700  109.009893

## 14.4 Additional Indexing Conventions

### 14.4.1 Slicing References Rows

In [37]:
print(data['Florida':'New York'])

            area       pop     density
Florida   170312  21538187  126.463121
New York  141297  20201249  142.970120

### 14.4.2 Masking References Rows

In [38]:
print(data[data.density > 120])

            area       pop     density
Florida   170312  21538187  126.463121
New York  141297  20201249  142.970120

💡 DataFrame에서 직접 indexing할 때는 렬이 아니라 행이 선택된다는 점을 기억!