# Chapter 13: Introducing Pandas Objects

In [61]:
import numpy as np
import pandas as pd

## 13.1 The Pandas Series Object

A Pandas Series is a one-dimensional array of indexed data. It can be created from a
list or array as follows:

In [62]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

Series attribute

In [63]:
# 값 확인 (NumPy 배열)
print(data.values)

# 인덱스 확인
print(data.index)

[0.25 0.5  0.75 1.  ]
RangeIndex(start=0, stop=4, step=1)

💡 data.values ​​is a NumPy array, and data.index is a Pandas Index object.

## 13.2 Series as Generalized NumPy Array

Explicit Index Specification

In [64]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [65]:
# 인덱스로 접근
print(data['b'])
print(data[['a', 'c']])

0.5
a    0.25
c    0.75
dtype: float64

Non-sequential index

In [66]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [67]:
print(data[5])

0.5

## 13.3 Series as Specialized Dictionary

Convert Dictionary to Series

In [68]:
population_dict = {'California': 39538223,
                   'Texas': 29145505,
                   'Florida': 21538187,
                   'New York': 20201249,
                   'Pennsylvania': 13002700}
population = pd.Series(population_dict)
population

California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
dtype: int64

Here, you can perform typical dictionary-style item access:

In [69]:
population['California']

np.int64(39538223)

However, unlike dictionaries, Series also supports array-style operations such as slicing:

In [70]:
population['California':'Florida']

California    39538223
Texas         29145505
Florida       21538187
dtype: int64

## 13.4 Constructing Series Objects

Method 1: Create from a list

In [71]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

Method 2: Create from a scalar value

In [72]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

Method 3: Create from a dictionary

In [73]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: str

Method 4: Explicitly specify an index

In [74]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[1, 2])

1    b
2    a
dtype: str

## 13.5 The Pandas DataFrame Object

A DataFrame is a two-dimensional labeled data structure.

In [75]:
area_dict = {
    'California': 423967,
    'Texas': 695662,
    'Florida': 170312,
    'New York': 141297,
    'Pennsylvania': 119280
}

area = pd.Series(area_dict)

In [76]:
# DataFrame Creation
states = pd.DataFrame({'population': population,
                       'area': area})

print(states)

              population    area
California      39538223  423967
Texas           29145505  695662
Florida         21538187  170312
New York        20201249  141297
Pennsylvania    13002700  119280

DataFrame attribute

In [77]:
# Row index
print(states.index)

# column index
print(states.columns)

Index(['California', 'Texas', 'Florida', 'New York', 'Pennsylvania'], dtype='str')
Index(['population', 'area'], dtype='str')

## 13.6 DataFrame as Generalized NumPy Array

In [78]:
# accessing value as Numpy array
print(states.values)

[[39538223   423967]
 [29145505   695662]
 [21538187   170312]
 [20201249   141297]
 [13002700   119280]]

## 13.7 DataFrame as Specialized Dictionary

In [79]:
# accessing column as key of dictionary
print(states['area'])   # return Series

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

## 13.8 Constructing DataFrame Objects

From single Series

In [80]:
pd.DataFrame(population, columns=['population'])

              population
California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700

From dictionary list

In [81]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]
print(pd.DataFrame(data))

   a  b
0  0  0
1  1  2
2  2  4

If there are missing keys

In [82]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

From 2D Numpy array

In [83]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

        foo       bar
a  0.659939  0.037002
b  0.232258  0.182784
c  0.743161  0.479461

From a structured array

In [84]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
print(A)
pd.DataFrame(A)

[(0, 0.) (0, 0.) (0, 0.)]

   A    B
0  0  0.0
1  0  0.0
2  0  0.0

## 13.9 The Pandas Index Object

Index as Immutable Array

In [85]:
ind = pd.Index([2, 3, 5, 7, 11])
print(ind[1])
print(ind[::2])

3
Index([2, 5, 11], dtype='int64')

💡 Index는 불변(immutable)입니다. 한 번 생성하면 수정할 수 없습니다.

In [ ]:
ind[1] = 0
# TypeError: Index does not support mutable operations

Index as Ordered Set

In [90]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

# 교집합
print(indA.intersection(indB))

# 합집합
print(indA.union(indB))

# 대칭차집합
print(indA.symmetric_difference(indB))

Index([3, 5, 7], dtype='int64')
Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')
Index([1, 2, 9, 11], dtype='int64')

💡 Index는 집합 연산을 지원합니다!